#!/usr/bin/env python3
"""Pre-compute the list of sahen (suru-verb) lemmas.

Reads all verb lemmas from data/wn+var_tk17.tab and data/wn-ntumc-jpn.xml,
checks each with jamdict, and writes the results to data/sahen_verbs.txt.

Run this once (or whenever the input data changes) before build_wnja.py.
The build script reads data/sahen_verbs.txt instead of calling jamdict at
build time, making builds much faster.
"""

import logging
import sys
from pathlib import Path
from xml.etree import ElementTree as ET

import jamdict

from build_wnja import (
    GODAN_ENDINGS,
    WNVAR_FILE,
    NTUMC_XML,
    desuru,
    ntumc_id_to_num,
)

SAHEN_FILE = Path("data/sahen_verbs.txt")
LOG_FILE = Path("detect_sahen.log")

logging.basicConfig(
    level=logging.INFO,
    format="%(levelname)s %(message)s",
    handlers=[
        logging.FileHandler(LOG_FILE, encoding="utf-8"),
        logging.StreamHandler(sys.stderr),
    ],
    force=True,
)
log = logging.getLogger("sahen")


def collect_verb_lemmas() -> set[str]:
    """Collect all canonical verb lemmas from wn+var and NTU-MC XML."""
    verb_lemmas: set[str] = set()

    # From wn+var_tk17.tab: any lemma whose synset ends in 'v'
    with open(WNVAR_FILE, encoding="utf-8") as fh:
        for raw in fh:
            if raw.startswith("#") or not raw.strip():
                continue
            row = [c.strip() for c in raw.split("\t")]
            if row[0].endswith("-v"):
                verb_lemmas.add(desuru(row[1]))

    # From NTU-MC XML: entries with partOfSpeech="v"
    tree = ET.parse(NTUMC_XML)
    root = tree.getroot()
    lexicon = root.find("Lexicon") or root
    for entry in lexicon.findall("LexicalEntry"):
        lemma_elem = entry.find("Lemma")
        if lemma_elem is not None and lemma_elem.get("partOfSpeech") == "v":
            verb_lemmas.add(desuru(lemma_elem.get("writtenForm", "")))

    verb_lemmas.discard("")
    return verb_lemmas


def check_sahen_jamdict(word: str, jam: jamdict.Jamdict) -> bool:
    """Check jamdict for explicit sahen (suru-verb) marking."""
    result = jam.lookup(word)
    for entry in result.entries:
        for sense in entry.senses:
            if "noun or participle which takes the aux. verb suru" in str(sense.pos):
                return True
    return False


def main() -> None:
    log.info("Collecting verb lemmas …")
    verb_lemmas = collect_verb_lemmas()
    log.info("  %d unique verb lemmas to check", len(verb_lemmas))

    # Fast pass: non-godan endings are always sahen (same fallback as old script)
    sahen: set[str] = set()
    needs_jamdict: list[str] = []
    for word in verb_lemmas:
        if not word:
            continue
        if word[-1] not in GODAN_ENDINGS:
            sahen.add(word)
        else:
            needs_jamdict.append(word)

    log.info(
        "  %d sahen by ending heuristic; %d need jamdict check",
        len(sahen), len(needs_jamdict),
    )

    log.info("Initialising jamdict …")
    jam = jamdict.Jamdict()

    for i, word in enumerate(sorted(needs_jamdict), 1):
        if check_sahen_jamdict(word, jam):
            sahen.add(word)
        if i % 1000 == 0:
            log.info("  processed %d / %d", i, len(needs_jamdict))

    log.info("Found %d sahen verbs out of %d", len(sahen), len(verb_lemmas))

    SAHEN_FILE.parent.mkdir(parents=True, exist_ok=True)
    with open(SAHEN_FILE, "w", encoding="utf-8") as fh:
        fh.write("# Sahen (suru) verbs — generated by detect_sahen.py\n")
        for word in sorted(sahen):
            fh.write(word + "\n")

    log.info("Written to %s", SAHEN_FILE)


if __name__ == "__main__":
    main()
